version: "3"
services:
  # Frontend
  postmate-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: jaskiratr/k8s-postmate-frontend
    ports:
      - 3000:3000
      - 80:80
    environment:
      - POSTMATE_ENVIRONMENT=local-microservice
    volumes:
      - ./frontend:/usr/src/app/
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - postmate-cms

  # CMS
  postmate-cms:
    build: ./cms
    image: jaskiratr/k8s-postmate-cms
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=postmate-mongodb
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./cms/strapi-app:/usr/src/api/strapi-app
    depends_on:
      - postmate-mongodb
    restart: always

  # MongoDB
  postmate-mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - "mongodbdata:/data/db"
    command: mongod --smallfiles --logpath=/dev/null

volumes:
  node_modules:
  mongodbdata:
    external: true
