apiVersion: apps/v1
kind: Deployment
metadata:
  name: postmate-mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: strapi
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc

# apiVersion: v1
# kind: Pod
# metadata:
#   name: postmate-mongodb
#   labels:
#     app: postmate-mongodb
# spec:
#   containers:
#     - name: postmate-mongodb
#       image: mongo
#       ports:
#         - containerPort: 27017
#       env:
#         - name: MONGO_INITDB_DATABASE
#           value: strapi
#       volumeMounts:
#         - name: mongo-persistent-storage
#           mountPath: /data/db
#   volumes:
#     - name: mongo-persistent-storage
#       persistentVolumeClaim:
#         claimName: mongo-pvc

---
kind: Service
apiVersion: v1
metadata:
  name: postmate-mongodb
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
