apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: "nginx-reverse-proxy:latest"
      imagePullPolicy: Never
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30090
      name: nuxt
    - protocol: TCP
      port: 8080
      nodePort: 30091
      name: strapi
  type: NodePort
