apiVersion: apps/v1
kind: Deployment
metadata:
  name: postmate-frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "k8s-postmate-frontend:latest"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3000
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: postmate-frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: "80"
      protocol: TCP
      port: 80
      nodePort: 30080
  type: NodePort
