apiVersion: v1
kind: Service
metadata:
  name: nuxt
  labels:
    app: nuxt
spec:
  selector:
    app: nuxt
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: strapi
  labels:
    app: strapi
spec:
  selector:
    app: strapi
  ports:
    - name: "1337"
      protocol: TCP
      port: 1337
      nodePort: 30083
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: strapi-mongodb
  labels:
    app: strapi-mongodb
spec:
  selector:
    app: strapi-mongodb
  ports:
    - port: 27017
      targetPort: 27017
