apiVersion: v1
kind: Pod
metadata:
  name: nuxt
  labels:
    app: nuxt
spec:
  containers:
    - name: nuxt
      image: "nuxt:latest"
      imagePullPolicy: Never
      ports:
        - name: http
          containerPort: 3000
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: strapi
  labels:
    app: strapi
spec:
  containers:
    - name: strapi
      image: strapi/strapi
      ports:
        - name: http
          containerPort: 1337
      env:
        - name: APP_NAME
          value: strapi-app
        - name: DATABASE_AUTHENTICATION_DATABASE
          value: strapi
        - name: DATABASE_CLIENT
          value: mongo
        - name: DATABASE_USERNAME
          value: ""
        - name: DATABASE_PASSWORD
          value: ""
        - name: DATABASE_HOST
          value: strapi-mongodb
        - name: DATABASE_NAME
          value: strapi
        - name: DATABASE_PORT
          value: "27017"
        - name: DATABASE_SSL
          value: "false"
        # - name: HOST
        #   value: localhost
      volumeMounts:
        - name: strapi-persistent-storage
          mountPath: /usr/src/api/strapi-app
  volumes:
    - name: strapi-persistent-storage
      # pointer to the configuration of HOW we want the mount to be implemented
      persistentVolumeClaim:
        claimName: strapi-pvc
---
# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strapi-pvc
spec:
  storageClassName: strapilocalstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# How do we want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: strapi-local-storage
spec:
  storageClassName: strapilocalstorage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/strapi-app"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: Pod
metadata:
  name: strapi-mongodb
  labels:
    app: strapi-mongodb
spec:
  containers:
    - name: strapi-mongodb
      image: mongo
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_DATABASE
          value: strapi
      volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
  volumes:
    - name: mongo-persistent-storage
      # pointer to the configuration of HOW we want the mount to be implemented
      persistentVolumeClaim:
        claimName: mongo-pvc
---
# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: mongolocalstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# How do we want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-local-storage
spec:
  storageClassName: mongolocalstorage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/strapi-mongodb"
    type: DirectoryOrCreate
