# CMS: PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cms-pvc
spec:
  storageClassName: cmsawsstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
# CMS: PVC Implementation
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cmsawsstorage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2

---
# MongoDB: PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: mongoawsstorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
# MongoDB: PVC Implementation
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongoawsstorage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mongo-local-storage
# spec:
#   storageClassName: mongoawsstorage
#   capacity:
#     storage: 2Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/data/postmate/mongodb"
#     type: DirectoryOrCreate
